---
#
# Configure asterisk
#
- name: install Asterisk
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
#  gather_facts: no
#  pre_tasks:
#    - name: install python2
#      raw: sudo apt-get -y install python-simplejson
#    - name: gather facts
#      setup:  

  roles:
    - asterisk
