---
- name: Install rabbit
  hosts: rabbit
  roles:
  - {role: 'rabbit', tags: 'rabbit'}

- name: Install mysql
  hosts: mysql
  roles:
  - {role: 'mysql', tags: 'mysql'}

- name: Install keystone
  hosts: keystone
  roles:
  - {role: 'keystone', tags: 'keystone'}

- name: Install glance
  hosts: glance
  roles:
  - {role: 'glance', tags: 'glance'}

- name: Install nova
  hosts: nova
  roles:
  - {role: 'nova', tags: 'nova'}

- name: Install placement
  hosts: placement
  roles:
  - {role: 'placement', tags: 'placement'}

- name: Install neutron
  hosts: neutron
  roles:
  - {role: 'neutron', tags: 'neutron'}

- name: Install compute
  hosts: compute-*
  roles:
  - {role: 'compute', tags: 'compute'}

- name: Install bastion
  hosts: bastion-*
  roles:
  - {role: 'bastion', tags: 'bastion'}

